{{- if .Values.fleetdm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleetdm.fullname" . }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fleetdm.service.type }}
  ports:
    - port: {{ .Values.fleetdm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.fleetdm.service.type "NodePort") .Values.fleetdm.service.nodePort }}
      nodePort: {{ .Values.fleetdm.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fleetdm.selectorLabels" . | nindent 4 }}
{{- end }}

